apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # CRITICAL: Added secrets to pull from Gitea
      imagePullSecrets:
        - name: gitea-creds
      containers:
      - name: nginx-frontend
        # Match the naming convention in your Jenkinsfile
        image: 74.242.218.126:3000/mohammed/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081 
  selector:
    app: frontend