apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      # This MUST be inside the pod spec
      imagePullSecrets:
        - name: gitea-creds
      containers:
        - name: fastapi-user-mgmt
          image: 74.242.218.126:3000/mohammed/user-mgmt-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
  selector:
    app: user-api